# config
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      default-filters:
        - name: Hystrix
          args:
            name : default
            fallbackUri: 'forward:/defaultfallback' 
  profiles:    active: dev
# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug
    redisratelimiter: debug