# 项目相关配置
czyl:
  # 名称
  name: webSocket示例
  description: webSocket示例
  # 版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/palform/uploadPath，Linux配置 /home/palform/uploadPath）
  profile: D:/palform/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  #不校验权限可访问
  permitAllUrls: /login/**
  rest-template:
    maxTotal: 300

# 日志配置
logging:
  level:
    com.czyl: debug
    org.springframework: warn
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
      
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 480
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.czyl.*.**.domain
    #,com.czyl.framework.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
# 代码生成
gen: 
  # 作者
  author: tanghx
  # 网关 /开头 结尾不带/
  gateWay: /file-api
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.czyl.project.file
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_