# 数据源配置
spring:
# 缓存 redis 配置
  redis:
    # 地址 如果要用单机redis 注释 cluster及以下，启用host
    password: Czyl2010!
    # 连接超时时间
    timeout: 12s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 64
        # 连接池的最大数据库连接数
        max-active: 64
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait-millis: -1
    cluster:
      nodes:
        - redis.czyl:30001
        - redis.czyl:30002
        - redis.czyl:30003
        - redis.czyl:30004
        - redis.czyl:30005
        - redis.czyl:30006
