# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
#      primary: master
      datasource:
        # 主库数据源
        master:
          enabled: true
          url: jdbc:mysql://161.189.1.115:13306/kelun_hnym?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        slave_1:
          enabled: false
          url: jdbc:mysql://161.189.1.115:13306/kelun_hnym?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        slave_2:
          enabled: false
          url: jdbc:mysql://161.189.1.115:13306/kelun_hnym?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        # 分布式ID数据源
        workerNode:
          # 数据源开关/默认关闭
          enabled: true
          url: jdbc:mysql://161.189.1.115:13306/kelun_hnym?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 3000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 3000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 30000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      resetStatEnable : false
      webStatFilter: 
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /czyldatasourceboard/*
        # 控制台管理用户名和密码
        login-username: 
        login-password: 
      filters: stat,wall
      filter:
        stat:
          # 慢SQL记录
          logSlowSql: true
          slowSqlMillis: 1000
          mergeSql: true
        wall:
          config:
            multiStatementAllow: true
# 缓存 redis 配置
  redis:
    # 地址 如果要用单机redis 注释 cluster及以下，启用host
    host: db.com
    # 端口，默认为6379
    port: 6379
    #password: czyl2010
    # 连接超时时间
    timeout: 12s

#elasticsearch服务配置
#  data:
#    elasticsearch:
#      cluster-name:  es-czyl
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true
#      properties:
#        transport:
#          tcp:  
#            connect_timeout: 120s
    
elasticsearch:
  schema: http
  address: 127.0.0.1:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100