# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      #      primary: master
      datasource:
        # 主库数据源
        master:
          url: jdbc:mysql://172.30.16.36:3306/kelun_dzjgm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        # 从库数据源
        slave_1:
          # 从数据源开关/默认关闭
          enabled: true
          url: jdbc:mysql://172.30.16.34:3306/kelun_dzjgm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        # 从库数据源
        slave_2:
          # 从数据源开关/默认关闭
          enabled: false
          url: jdbc:mysql://172.30.16.34:33063/kelun_dzjgm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
        # 分布式ID数据源
        workerNode:
          # 从数据源开关/默认关闭
          enabled: true
          url: jdbc:mysql://172.30.16.36:3306/kelun_dzjgm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Czyl2010!
    druid:
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 3000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 3000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 30000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      resetStatEnable: false
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /czyldatasourceboard/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filters: stat,wall
      filter:
        stat:
          # 慢SQL记录
          logSlowSql: true
          slowSqlMillis: 3000
          mergeSql: true
        wall:
          config:
            multiStatementAllow: true
  # 缓存 redis 配置
  redis:
    # 地址
    #    host: db.com
    # 端口，默认为6379
    #    port: 6379
    password: czyl2010
    # 连接超时时间
    timeout: 12s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 20
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait-millis: -1
    cluster:
      nodes:
        - 172.30.16.36:30001
        - 172.30.16.36:30002
        - 172.30.16.36:30003
        - 172.30.16.36:30004
        - 172.30.16.36:30005
        - 172.30.16.36:30006
        - 172.30.16.34:30001
        - 172.30.16.34:30002
        - 172.30.16.34:30003
        - 172.30.16.34:30004
        - 172.30.16.34:30005
        - 172.30.16.34:30006
  data:
    mongodb:
      uri: mongodb://czyl:Czyl2010!@172.30.16.36:27017,172.30.16.36:27018/klemc?authSource=klemc&replicaSet=CzylCluster&authMechanism=SCRAM-SHA-1&minpoolsize=50&maxpoolsize=500
#更多参数见com.mongodb.ConnectionString

# SAP 配置
emc:
  sap:
    url: http://172.30.4.11:50000
    #    url: http://52.83.32.16:50000
    user: POD_DZ
    pass: 12345678A
    #监管码新增的时候查询地址
    fetchData: /RESTAdapter/SI_DZJG_OUT_CX
